spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/springbootdata?/characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
    username: root
    password: Zjh20040301
  jpa:
    show-sql: true